use_frameworks!

platform :ios, '8.0'

target 'ZZFileManager_Example' do
  pod 'ZZFileManager', :path => '../'

  target 'ZZFileManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
